export default `
Nightfall|極夜|極夜|극야|Noche|Nuit|Polarnacht|Noite|Полярная ночь|الليل القطبي
License verified.|授權已驗證。|ライセンスを確認しました。|라이선스가 확인되었습니다.|Licencia verificada.|Licence vérifiée.|Lizenz verifiziert.|Licença verificada.|Лицензия проверена.|تم التحقق من الترخيص.
Offline — verification required in {0} days.|目前離線，需於 {0} 天內連線驗證。|オフラインです。{0} 日以内にオンライン確認が必要です。|오프라인입니다. {0}일 이내에 온라인 확인이 필요합니다.|Sin conexión: verifica la licencia en {0} días.|Hors ligne : vérification requise sous {0} jours.|Offline – Prüfung innerhalb von {0} Tagen erforderlich.|Offline: verificação necessária em {0} dias.|Нет сети. Проверка потребуется через {0} дней.|غير متصل — يلزم التحقق خلال {0} أيام.
License could not be verified. Connect to the internet and try again.|無法驗證授權，請連線後再試。|ライセンスを確認できません。ネットに接続して再試行してください。|라이선스를 확인할 수 없습니다. 인터넷 연결 후 재시도하세요.|No se pudo verificar la licencia. Conéctate e inténtalo de nuevo.|Impossible de vérifier la licence. Connectez-vous et réessayez.|Lizenz konnte nicht geprüft werden. Internetverbindung herstellen und erneut versuchen.|Não foi possível verificar a licença. Conecte-se e tente novamente.|Не удалось проверить лицензию. Подключитесь к интернету и повторите.|تعذر التحقق من الترخيص. اتصل بالإنترنت وأعد المحاولة.
New version available|發現新版本|新バージョンがあります|새 버전이 있습니다|Nueva versión disponible|Nouvelle version disponible|Neue Version verfügbar|Nova versão disponível|Доступна новая версия|يتوفر إصدار جديد
Enter an activation code.|請輸入啟用碼。|アクティベーションコードを入力してください。|활성화 코드를 입력하세요.|Introduce un código de activación.|Saisissez un code d’activation.|Aktivierungscode eingeben.|Insira um código de ativação.|Введите код активации.|أدخل رمز التفعيل.
Activating…|啟用中…|有効化中…|활성화 중…|Activando…|Activation…|Wird aktiviert…|Ativando…|Активация…|جارٍ التفعيل…
Activation failed.|啟用失敗。|有効化に失敗しました。|활성화에 실패했습니다.|Error de activación.|Échec de l’activation.|Aktivierung fehlgeschlagen.|Falha na ativação.|Ошибка активации.|فشل التفعيل.
Activated successfully and bound to this device.|啟用成功，已綁定此裝置。|有効化され、この端末に登録されました。|활성화되어 이 기기에 연결되었습니다.|Activada y vinculada a este dispositivo.|Activée et liée à cet appareil.|Aktiviert und an dieses Gerät gebunden.|Ativada e vinculada a este dispositivo.|Активирована и привязана к устройству.|تم التفعيل والربط بهذا الجهاز.
License removed from this device. You can activate again later.|已移除此裝置授權，可稍後重新啟用。|この端末のライセンスを削除しました。後で再有効化できます。|이 기기의 라이선스를 제거했습니다. 나중에 다시 활성화할 수 있습니다.|Licencia retirada del dispositivo. Puedes activarla más tarde.|Licence retirée de cet appareil. Vous pourrez la réactiver.|Lizenz von diesem Gerät entfernt. Erneute Aktivierung ist später möglich.|Licença removida deste dispositivo. Você pode ativar novamente depois.|Лицензия удалена с устройства. Позже можно активировать снова.|أزيل الترخيص من هذا الجهاز. يمكنك التفعيل مجدداً لاحقاً.
Version update|版本更新|バージョン更新|버전 업데이트|Actualización de versión|Mise à jour de version|Versionsupdate|Atualização de versão|Обновление версии|تحديث الإصدار
Notification details|通知詳情|通知の詳細|알림 상세|Detalles de notificación|Détails de la notification|Benachrichtigungsdetails|Detalhes da notificação|Подробности уведомления|تفاصيل الإشعار
Open download page|開啟下載頁面|ダウンロードページを開く|다운로드 페이지 열기|Abrir página de descarga|Ouvrir la page de téléchargement|Downloadseite öffnen|Abrir página de download|Открыть страницу загрузки|فتح صفحة التنزيل
Acknowledge|確認|確認|확인|Confirmar|Confirmer|Bestätigen|Confirmar|Подтвердить|تأكيد
Notification center|通知中心|通知センター|알림 센터|Centro de notificaciones|Centre de notifications|Benachrichtigungszentrale|Central de notificações|Центр уведомлений|مركز الإشعارات
No notifications yet. While the app is running, task results, announcements, and alerts will appear here.|尚無通知。軟體執行時，任務結果、公告與提醒會顯示於此。|通知はまだありません。アプリ実行中に結果・お知らせ・警告がここに表示されます。|알림이 없습니다. 앱 실행 중 작업 결과, 공지 및 경고가 여기에 표시됩니다.|Aún no hay notificaciones. Con la aplicación abierta, los resultados, anuncios y alertas aparecerán aquí.|Aucune notification. Lorsque l’application est ouverte, résultats, annonces et alertes apparaissent ici.|Noch keine Benachrichtigungen. Während die App läuft, erscheinen hier Ergebnisse, Ankündigungen und Warnungen.|Sem notificações. Com o aplicativo aberto, resultados, avisos e alertas aparecem aqui.|Уведомлений нет. Во время работы приложения здесь появятся результаты, объявления и предупреждения.|لا توجد إشعارات بعد. أثناء تشغيل التطبيق تظهر هنا النتائج والإعلانات والتنبيهات.
Mark all as read|全部標示為已讀|すべて既読にする|모두 읽음 처리|Marcar todo como leído|Tout marquer comme lu|Alle als gelesen markieren|Marcar tudo como lido|Отметить всё прочитанным|تحديد الكل كمقروء
Clear all|清除全部|すべて消去|모두 지우기|Borrar todo|Tout effacer|Alle löschen|Limpar tudo|Очистить всё|مسح الكل
Activation code and device access|啟用碼與裝置授權|コードと端末のライセンス|활성화 코드 및 기기 권한|Código y acceso del dispositivo|Code et accès de l’appareil|Aktivierungscode und Gerätezugriff|Código e acesso do dispositivo|Код активации и доступ устройства|رمز التفعيل وصلاحية الجهاز
In-app alerts while the app is running|軟體執行時的應用程式內提醒|アプリ実行中の通知|앱 실행 중 내부 알림|Alertas dentro de la aplicación abierta|Alertes pendant l’exécution de l’application|Hinweise während die App läuft|Alertas enquanto o aplicativo está aberto|Оповещения во время работы приложения|تنبيهات داخل التطبيق أثناء تشغيله
Version, license, and official links|版本、授權與官方連結|バージョン・ライセンス・公式リンク|버전, 라이선스 및 공식 링크|Versión, licencia y enlaces oficiales|Version, licence et liens officiels|Version, Lizenz und offizielle Links|Versão, licença e links oficiais|Версия, лицензия и официальные ссылки|الإصدار والترخيص والروابط الرسمية
Manage local models and cloud APIs. Changes are saved automatically.|管理本機模型與雲端 API，變更會自動儲存。|ローカルモデルとクラウド API を管理。変更は自動保存されます。|로컬 모델과 클라우드 API를 관리합니다. 변경 사항은 자동 저장됩니다.|Administra modelos locales y API en la nube. Los cambios se guardan automáticamente.|Gérez modèles locaux et API cloud. Les changements sont enregistrés automatiquement.|Lokale Modelle und Cloud-APIs verwalten. Änderungen werden automatisch gespeichert.|Gerencie modelos locais e APIs na nuvem. As alterações são salvas automaticamente.|Управляйте локальными моделями и облачными API. Изменения сохраняются автоматически.|إدارة النماذج المحلية وواجهات API السحابية. تُحفظ التغييرات تلقائياً.
Save multiple local models and switch between them in the composer.|可儲存多個本機模型，並於輸入框切換。|複数のローカルモデルを保存し、入力欄で切り替えられます。|로컬 모델을 여러 개 저장하고 입력창에서 전환하세요.|Guarda varios modelos locales y cámbialos en el cuadro de entrada.|Enregistrez plusieurs modèles locaux et changez-les dans la saisie.|Mehrere lokale Modelle speichern und im Eingabefeld wechseln.|Salve vários modelos locais e alterne na caixa de entrada.|Сохраняйте несколько локальных моделей и переключайте их в поле ввода.|احفظ عدة نماذج محلية وبدّل بينها في حقل الإدخال.
No local models yet. Click ＋ to add one.|尚無本機模型，點 ＋ 新增。|ローカルモデルがありません。＋ で追加。|로컬 모델이 없습니다. ＋로 추가하세요.|Sin modelos locales. Pulsa ＋ para añadir.|Aucun modèle local. Cliquez sur ＋ pour en ajouter.|Keine lokalen Modelle. Mit ＋ hinzufügen.|Sem modelos locais. Clique em ＋ para adicionar.|Локальных моделей нет. Нажмите ＋ для добавления.|لا توجد نماذج محلية. اضغط ＋ للإضافة.
Delete current|刪除目前項目|現在の項目を削除|현재 항목 삭제|Eliminar actual|Supprimer l’élément actuel|Aktuellen Eintrag löschen|Excluir atual|Удалить текущий|حذف الحالي
Requests are sent only to the local address you enter.|請求僅傳送至填寫的本機位址。|リクエストは指定したローカルアドレスにのみ送信されます。|요청은 입력한 로컬 주소로만 전송됩니다.|Las solicitudes solo se envían a la dirección local indicada.|Les demandes sont envoyées uniquement à l’adresse locale indiquée.|Anfragen werden nur an die angegebene lokale Adresse gesendet.|As solicitações são enviadas apenas ao endereço local informado.|Запросы отправляются только на указанный локальный адрес.|تُرسل الطلبات إلى العنوان المحلي الذي تدخله فقط.
Connection not tested|尚未測試連線|接続は未テスト|연결 미테스트|Conexión sin probar|Connexion non testée|Verbindung nicht getestet|Conexão não testada|Подключение не проверено|لم يُختبر الاتصال
Each model keeps its own protocol, endpoint, and model name.|各模型分別儲存協定、位址與模型名稱。|モデルごとにプロトコル・アドレス・名前を保存します。|모델별로 프로토콜, 주소 및 모델 이름을 저장합니다.|Cada modelo guarda su protocolo, dirección y nombre.|Chaque modèle conserve son protocole, son adresse et son nom.|Jedes Modell speichert Protokoll, Adresse und Modellnamen separat.|Cada modelo mantém seu protocolo, endereço e nome.|Каждая модель хранит свой протокол, адрес и имя.|يحتفظ كل نموذج بالبروتوكول والعنوان والاسم الخاص به.
No cloud models yet. Click ＋ to add one.|尚無雲端模型，點 ＋ 新增。|クラウドモデルがありません。＋ で追加。|클라우드 모델이 없습니다. ＋로 추가하세요.|Sin modelos en la nube. Pulsa ＋ para añadir.|Aucun modèle cloud. Cliquez sur ＋ pour en ajouter.|Keine Cloud-Modelle. Mit ＋ hinzufügen.|Sem modelos na nuvem. Clique em ＋ para adicionar.|Облачных моделей нет. Нажмите ＋ для добавления.|لا توجد نماذج سحابية. اضغط ＋ للإضافة.
API format|API 格式|API 形式|API 형식|Formato de API|Format d’API|API-Format|Formato de API|Формат API|صيغة API
Endpoint|介面位址|エンドポイント|엔드포인트|Dirección del servicio|Adresse du service|Schnittstellenadresse|Endereço do serviço|Адрес API|عنوان الواجهة
API key|API 金鑰|API キー|API 키|Clave de API|Clé API|API-Schlüssel|Chave de API|Ключ API|مفتاح API
Stored only for this session|僅儲存於本次工作階段|このセッションのみ保存|이 세션에만 저장|Solo para esta sesión|Pour cette session seulement|Nur für diese Sitzung gespeichert|Somente para esta sessão|Только на время сеанса|يُحفظ لهذه الجلسة فقط
Configured and available in the composer|已設定，可於輸入框選取|設定済み・入力欄から選択可能|설정됨, 입력창에서 선택 가능|Configurado y disponible en la entrada|Configuré et disponible dans la saisie|Konfiguriert und im Eingabefeld verfügbar|Configurado e disponível na entrada|Настроено, доступно в поле ввода|مُعدّ ومتاح في حقل الإدخال
Not configured|尚未設定|未設定|설정되지 않음|Sin configurar|Non configuré|Nicht konfiguriert|Não configurado|Не настроено|غير مُعدّ
Receive notifications only while Wendaflow is running. No background connection is kept after you close the app.|僅於 Wendaflow 執行時接收通知，關閉後不保留背景連線。|Wendaflow 実行中のみ通知を受信。終了後はバックグラウンド接続しません。|Wendaflow 실행 중에만 알림을 받습니다. 종료 후에는 백그라운드 연결을 유지하지 않습니다.|Recibe notificaciones solo con Wendaflow abierto. Al cerrarlo no queda conexión en segundo plano.|Les notifications arrivent uniquement lorsque Wendaflow fonctionne. Aucune connexion ne reste après fermeture.|Benachrichtigungen nur bei laufendem Wendaflow. Nach dem Schließen bleibt keine Hintergrundverbindung.|Receba notificações somente com Wendaflow aberto. Ao fechar, não há conexão em segundo plano.|Уведомления поступают только при запущенном Wendaflow. После закрытия фонового подключения нет.|تُستقبل الإشعارات أثناء تشغيل Wendaflow فقط. لا يبقى اتصال في الخلفية بعد الإغلاق.
When enabled, new messages appear as a pop-up and remain in Notification Center.|開啟後新訊息會彈出，並保留於通知中心。|有効にすると新着をポップアップ表示し、通知センターに保存します。|켜면 새 메시지가 팝업으로 표시되고 알림 센터에 남습니다.|Los mensajes nuevos aparecen como ventanas emergentes y quedan en el centro de notificaciones.|Les nouveaux messages s’affichent en fenêtre et restent dans le centre de notifications.|Neue Nachrichten erscheinen als Popup und bleiben in der Benachrichtigungszentrale.|Novas mensagens aparecem em pop-up e ficam na central de notificações.|Новые сообщения всплывают на экране и остаются в центре уведомлений.|تظهر الرسائل الجديدة في نافذة منبثقة وتبقى في مركز الإشعارات.
Notifications sync automatically. Address setup is not required, and confirmation-required notices remain until acknowledged.|通知自動同步，無須設定地址；需確認的通知會保留至手動確認。|通知は自動同期。アドレス設定は不要で、要確認通知は確認するまで残ります。|알림은 자동 동기화됩니다. 주소 설정은 필요 없으며 확인 필수 알림은 확인할 때까지 남습니다.|Las notificaciones se sincronizan sin configurar direcciones. Las que requieren confirmación permanecen hasta confirmarlas.|Synchronisation automatique sans adresse à configurer. Les avis à confirmer restent jusqu’à confirmation.|Automatische Synchronisation ohne Adresseinstellung. Bestätigungspflichtige Hinweise bleiben bis zur Bestätigung.|Notificações sincronizam sem configurar endereço. As que exigem confirmação permanecem até serem confirmadas.|Уведомления синхронизируются без настройки адреса. Требующие подтверждения остаются до подтверждения.|تتزامن الإشعارات تلقائياً دون ضبط عنوان. تبقى الإشعارات التي تتطلب التأكيد حتى تؤكدها.
This device ID|本機裝置 ID|この端末の ID|이 기기 ID|ID de este dispositivo|ID de cet appareil|ID dieses Geräts|ID deste dispositivo|ID этого устройства|معرّف هذا الجهاز
License & activation|授權與啟用|ライセンスと有効化|라이선스 및 활성화|Licencia y activación|Licence et activation|Lizenz und Aktivierung|Licença e ativação|Лицензия и активация|الترخيص والتفعيل
An activation code binds to this device on first use. Revocation or expiry takes effect at the next online verification.|啟用碼首次使用會綁定本機。撤銷或到期於下次連線驗證生效。|コードは初回使用時にこの端末へ登録されます。失効や期限切れは次回オンライン確認時に反映されます。|활성화 코드는 최초 사용 시 기기에 연결됩니다. 취소나 만료는 다음 온라인 확인 시 반영됩니다.|El código se vincula al dispositivo al usarlo. La revocación o caducidad se aplica en la próxima verificación en línea.|Le code se lie à l’appareil à la première utilisation. Révocation ou expiration s’applique à la prochaine vérification en ligne.|Der Code bindet sich bei erster Nutzung an dieses Gerät. Widerruf oder Ablauf wirken bei der nächsten Onlineprüfung.|O código vincula-se ao dispositivo no primeiro uso. Revogação ou expiração vale na próxima verificação online.|При первом использовании код привязывается к устройству. Отзыв или истечение срока учитываются при следующей онлайн-проверке.|يرتبط الرمز بهذا الجهاز عند أول استخدام. يسري الإلغاء أو انتهاء الصلاحية عند التحقق التالي عبر الإنترنت.
Valid until|有效至|有効期限|유효 기한|Válida hasta|Valide jusqu’au|Gültig bis|Válida até|Действует до|صالح حتى
Perpetual license|永久授權|無期限ライセンス|영구 라이선스|Licencia perpetua|Licence perpétuelle|Unbefristete Lizenz|Licença perpétua|Бессрочная лицензия|ترخيص دائم
Bound to this device.|已綁定此裝置。|この端末に登録済み。|이 기기에 연결됨.|Vinculada a este dispositivo.|Liée à cet appareil.|An dieses Gerät gebunden.|Vinculada a este dispositivo.|Привязана к этому устройству.|مرتبط بهذا الجهاز.
Remove local license|移除本機授權|この端末のライセンスを削除|로컬 라이선스 제거|Quitar licencia local|Retirer la licence locale|Lokale Lizenz entfernen|Remover licença local|Удалить локальную лицензию|إزالة الترخيص المحلي
Activate this device|啟用此裝置|この端末を有効化|이 기기 활성화|Activar este dispositivo|Activer cet appareil|Dieses Gerät aktivieren|Ativar este dispositivo|Активировать устройство|تفعيل هذا الجهاز
Back up or restore complete canvases, including nodes, attachments, and layout.|備份或還原完整畫布，包含節點、附件與版面配置。|ノード、添付、配置を含むキャンバス全体をバックアップ・復元。|노드, 첨부 및 배치를 포함한 전체 캔버스를 백업하거나 복원합니다.|Respalda o restaura lienzos completos, con nodos, adjuntos y diseño.|Sauvegardez ou restaurez les canevas complets, avec nœuds, pièces jointes et disposition.|Komplette Leinwände mit Knoten, Anhängen und Layout sichern oder wiederherstellen.|Faça backup ou restaure telas completas com nós, anexos e layout.|Сохраняйте и восстанавливайте холсты целиком, включая узлы, вложения и расположение.|نسخ احتياطي أو استعادة لوحات كاملة تشمل العقد والمرفقات والتخطيط.
Wendaflow canvas file|Wendaflow 畫布檔案|Wendaflow キャンバスファイル|Wendaflow 캔버스 파일|Archivo de lienzo Wendaflow|Fichier de canevas Wendaflow|Wendaflow-Leinwanddatei|Arquivo de tela Wendaflow|Файл холста Wendaflow|ملف لوحة Wendaflow
Save the complete project in .wdf format|以 .wdf 格式儲存完整專案|プロジェクト全体を .wdf 形式で保存|전체 프로젝트를 .wdf 형식으로 저장|Guarda el proyecto completo en formato .wdf|Enregistrer le projet complet au format .wdf|Gesamtes Projekt im Format .wdf speichern|Salve o projeto completo em .wdf|Сохранить проект целиком в формате .wdf|حفظ المشروع كاملاً بصيغة .wdf
About Wendaflow|關於 Wendaflow|Wendaflow について|Wendaflow 정보|Acerca de Wendaflow|À propos de Wendaflow|Über Wendaflow|Sobre o Wendaflow|О Wendaflow|حول Wendaflow
A spatial workspace for conversations, context, and execution.|對話、上下文與執行的空間工作區。|対話・コンテキスト・実行をつなぐ空間ワークスペース。|대화, 문맥, 실행을 위한 공간형 작업 환경.|Un espacio visual para conversaciones, contexto y ejecución.|Un espace visuel pour les conversations, le contexte et l’exécution.|Ein räumlicher Arbeitsbereich für Gespräche, Kontext und Ausführung.|Um espaço visual para conversas, contexto e execução.|Пространство для диалогов, контекста и выполнения задач.|مساحة مرئية للمحادثات والسياق والتنفيذ.
Let conversations branch freely|讓對話自由分岔|対話を自由に分岐させよう|대화를 자유롭게 분기하세요|Deja que las conversaciones se ramifiquen|Laissez les conversations se ramifier|Gespräche frei verzweigen lassen|Deixe as conversas se ramificarem|Пусть разговоры свободно ветвятся|دع المحادثات تتفرّع بحرية
License status|授權狀態|ライセンス状態|라이선스 상태|Estado de licencia|État de la licence|Lizenzstatus|Status da licença|Состояние лицензии|حالة الترخيص
Enabled|已開啟|有効|활성화됨|Activado|Activé|Aktiviert|Ativado|Включено|مفعّل
Disabled|已關閉|無効|비활성화됨|Desactivado|Désactivé|Deaktiviert|Desativado|Выключено|معطّل
Wendaflow sends requests only through the model connections you configure. Model keys and canvas data stay managed by this device.|Wendaflow 只透過你設定的模型連線傳送請求；模型金鑰與畫布資料由本機管理。|Wendaflow は設定したモデル接続経由でのみ送信します。モデルキーとキャンバスデータはこの端末で管理します。|Wendaflow는 설정한 모델 연결로만 요청을 전송합니다. 모델 키와 캔버스 데이터는 이 기기에서 관리합니다.|Wendaflow envía solicitudes solo por las conexiones configuradas. Este dispositivo gestiona claves y datos del lienzo.|Wendaflow utilise uniquement les connexions configurées. Les clés des modèles et les données du canevas sont gérées sur cet appareil.|Wendaflow sendet Anfragen nur über konfigurierte Modellverbindungen. Schlüssel und Leinwanddaten werden auf diesem Gerät verwaltet.|Wendaflow envia solicitações apenas pelas conexões configuradas. Chaves e dados da tela são gerenciados neste dispositivo.|Wendaflow отправляет запросы только через настроенные подключения. Ключи моделей и данные холста управляются на этом устройстве.|يرسل Wendaflow الطلبات عبر اتصالات النماذج التي تضبطها فقط. تُدار المفاتيح وبيانات اللوحة على هذا الجهاز.
Sponsor|贊助|スポンサー|후원|Patrocinar|Soutenir|Unterstützen|Apoiar|Поддержать|دعم
Support continued Wendaflow development|支持 Wendaflow 持續開發|Wendaflow の継続開発を支援|Wendaflow의 지속적인 개발 지원|Apoyar el desarrollo continuo de Wendaflow|Soutenir le développement continu de Wendaflow|Die Weiterentwicklung von Wendaflow unterstützen|Apoie o desenvolvimento contínuo do Wendaflow|Поддержать дальнейшую разработку Wendaflow|دعم تطوير Wendaflow المستمر
Sponsor Wendaflow|贊助 Wendaflow|Wendaflow を支援|Wendaflow 후원|Patrocinar Wendaflow|Soutenir Wendaflow|Wendaflow unterstützen|Apoiar o Wendaflow|Поддержать Wendaflow|ادعم Wendaflow
If Wendaflow helps you, you can support its continued development through any option below. Click a QR code to enlarge it.|如果 Wendaflow 對你有幫助，歡迎透過下列任一方式支持後續開發。點擊 QR 碼可放大查看。|Wendaflow がお役に立った場合は、以下のいずれかの方法で開発を支援できます。QR コードをクリックすると拡大できます。|Wendaflow가 도움이 되었다면 아래 방법 중 하나로 개발을 후원해 주세요. QR 코드를 클릭하면 확대됩니다.|Si Wendaflow te ayuda, puedes apoyar su desarrollo con cualquiera de las opciones siguientes. Haz clic en el código QR para ampliarlo.|Si Wendaflow vous aide, vous pouvez soutenir son développement avec l’une des options ci-dessous. Cliquez sur le QR code pour l’agrandir.|Wenn Wendaflow dir hilft, kannst du die Weiterentwicklung mit einer der folgenden Optionen unterstützen. Klicke den QR-Code zum Vergrößern an.|Se o Wendaflow ajuda você, apoie o desenvolvimento contínuo por qualquer opção abaixo. Clique no QR code para ampliar.|Если Wendaflow вам помогает, поддержите его дальнейшую разработку любым из способов ниже. Нажмите QR-код для увеличения.|إذا كان Wendaflow مفيداً لك، يمكنك دعم تطويره المستمر عبر أي خيار أدناه. انقر رمز QR لتكبيره.
WeChat Pay|微信支付|WeChat Pay|위챗 페이|WeChat Pay|WeChat Pay|WeChat Pay|WeChat Pay|WeChat Pay|WeChat Pay
WeChat Pay recommended|推薦使用微信支付|WeChat Pay を推奨|위챗 페이 권장|Se recomienda WeChat Pay|WeChat Pay recommandé|WeChat Pay empfohlen|WeChat Pay recomendado|Рекомендуется WeChat Pay|يوصى باستخدام WeChat Pay
Alipay|支付寶|Alipay|알리페이|Alipay|Alipay|Alipay|Alipay|Alipay|Alipay
Scan with Alipay|使用支付寶掃碼|Alipay でスキャン|알리페이로 스캔|Escanear con Alipay|Scanner avec Alipay|Mit Alipay scannen|Escaneie com o Alipay|Сканировать через Alipay|امسح عبر Alipay
Binance Pay|幣安支付|Binance Pay|바이낸스 페이|Binance Pay|Binance Pay|Binance Pay|Binance Pay|Binance Pay|Binance Pay
Scan with Binance App|使用幣安 App 掃碼|Binance アプリでスキャン|바이낸스 앱으로 스캔|Escanear con la app de Binance|Scanner avec l’app Binance|Mit der Binance-App scannen|Escaneie com o app Binance|Сканировать в приложении Binance|امسح عبر تطبيق Binance
USDT · TRON|USDT · TRON|USDT · TRON|USDT · TRON|USDT · TRON|USDT · TRON|USDT · TRON|USDT · TRON|USDT · TRON|USDT · TRON
TRON network only|僅支援 TRON 網路|TRON ネットワークのみ|TRON 네트워크만 지원|Solo red TRON|Réseau TRON uniquement|Nur TRON-Netzwerk|Somente rede TRON|Только сеть TRON|شبكة TRON فقط
sponsorship QR code|贊助 QR 碼|支援用 QR コード|후원 QR 코드|Código QR de patrocinio|QR code de soutien|Unterstützungs-QR-Code|QR code de apoio|QR-код для поддержки|رمز QR للدعم
Click to enlarge|點擊放大|クリックして拡大|클릭하여 확대|Haz clic para ampliar|Cliquer pour agrandir|Zum Vergrößern klicken|Clique para ampliar|Нажмите для увеличения|انقر للتكبير
Thank you — your support directly helps Wendaflow keep improving.|感謝你的支持，它會直接幫助 Wendaflow 持續改進。|ご支援ありがとうございます。Wendaflow の継続的な改善に直接役立ちます。|후원해 주셔서 감사합니다. Wendaflow의 지속적인 개선에 직접 도움이 됩니다.|Gracias: tu apoyo ayuda directamente a que Wendaflow siga mejorando.|Merci : votre soutien aide directement Wendaflow à continuer de s’améliorer.|Danke — deine Unterstützung hilft Wendaflow direkt, sich weiter zu verbessern.|Obrigado — seu apoio ajuda diretamente o Wendaflow a continuar melhorando.|Спасибо — ваша поддержка напрямую помогает Wendaflow становиться лучше.|شكراً لك — دعمك يساعد Wendaflow مباشرة على الاستمرار في التحسن.
Copy address|複製地址|アドレスをコピー|주소 복사|Copiar dirección|Copier l’adresse|Adresse kopieren|Copiar endereço|Копировать адрес|نسخ العنوان
Copied|已複製|コピー済み|복사됨|Copiado|Copié|Kopiert|Copiado|Скопировано|تم النسخ
`;
