export default `
Plugins|外掛|プラグイン|플러그인|Complementos|Extensions|Plugins|Plugins|Плагины|الإضافات
Extensions are coming soon|擴充功能即將推出|拡張機能は近日登場|확장 기능이 곧 제공됩니다|Las extensiones llegarán pronto|Les extensions arrivent bientôt|Erweiterungen folgen bald|As extensões estarão disponíveis em breve|Расширения появятся скоро|الإضافات قادمة قريباً
Extensions are being prepared.|擴充功能正在準備中。|拡張機能を準備中です。|확장 기능을 준비하고 있습니다.|Se están preparando extensiones.|Les extensions sont en préparation.|Erweiterungen werden vorbereitet.|As extensões estão sendo preparadas.|Расширения готовятся.|يجري إعداد الإضافات.
Coming soon|敬請期待|近日公開|곧 출시|Próximamente|Bientôt disponible|Demnächst verfügbar|Em breve|Скоро|قريباً
You will be able to discover and manage Wendaflow extensions here.|未來你可在此探索與管理 Wendaflow 擴充功能。|ここで Wendaflow 拡張機能を見つけて管理できるようになります。|여기에서 Wendaflow 확장 기능을 찾아 관리할 수 있게 됩니다.|Aquí podrás descubrir y gestionar extensiones de Wendaflow.|Vous pourrez découvrir et gérer les extensions Wendaflow ici.|Hier können Sie Wendaflow-Erweiterungen entdecken und verwalten.|Aqui você poderá descobrir e gerenciar extensões do Wendaflow.|Здесь вы сможете находить и управлять расширениями Wendaflow.|ستتمكن هنا من اكتشاف إضافات Wendaflow وإدارتها.
Software updates|軟體更新|ソフトウェア更新|소프트웨어 업데이트|Actualizaciones de software|Mises à jour logicielles|Softwareupdates|Atualizações de software|Обновления программного обеспечения|تحديثات البرنامج
Check for updates|檢查更新|更新を確認|업데이트 확인|Buscar actualizaciones|Rechercher des mises à jour|Nach Updates suchen|Verificar atualizações|Проверить обновления|التحقق من التحديثات
Checking for updates…|正在檢查更新…|更新を確認中…|업데이트 확인 중…|Buscando actualizaciones…|Recherche de mises à jour…|Suche nach Updates…|Verificando atualizações…|Проверка обновлений…|جارٍ التحقق من التحديثات…
Checking…|正在檢查…|確認中…|확인 중…|Comprobando…|Vérification…|Wird geprüft…|Verificando…|Проверка…|جارٍ التحقق…
Update check failed|檢查更新失敗|更新の確認に失敗しました|업데이트 확인 실패|Falló la comprobación de actualizaciones|Échec de la vérification des mises à jour|Update-Prüfung fehlgeschlagen|Falha na verificação de atualizações|Не удалось проверить обновления|فشل التحقق من التحديثات
You’re up to date|已是最新版本|最新の状態です|최신 버전입니다|Estás al día|Vous êtes à jour|Sie sind auf dem neuesten Stand|Você está atualizado|У вас актуальная версия|لديك أحدث إصدار
You are up to date.|目前已是最新版本。|すでに最新です。|이미 최신 버전입니다.|Ya tienes la versión más reciente.|Vous disposez déjà de la dernière version.|Sie verwenden bereits die neueste Version.|Você já está na versão mais recente.|У вас уже установлена последняя версия.|لديك بالفعل أحدث إصدار.
An update is available in Notification Center.|通知中心已有可用更新。|通知センターに更新があります。|알림 센터에 업데이트가 있습니다.|Hay una actualización disponible en el Centro de notificaciones.|Une mise à jour est disponible dans le Centre de notifications.|Im Benachrichtigungszentrum ist ein Update verfügbar.|Há uma atualização disponível na Central de notificações.|В Центре уведомлений доступно обновление.|يتوفر تحديث في مركز الإشعارات.
Could not reach the update service. Please try again.|無法連線更新服務，請稍後再試。|更新サービスに接続できません。後でもう一度お試しください。|업데이트 서비스에 연결할 수 없습니다. 잠시 후 다시 시도하세요.|No se pudo acceder al servicio de actualizaciones. Inténtalo de nuevo más tarde.|Impossible d’accéder au service de mise à jour. Réessayez plus tard.|Der Update-Dienst ist nicht erreichbar. Bitte später erneut versuchen.|Não foi possível acessar o serviço de atualização. Tente novamente mais tarde.|Не удалось подключиться к службе обновлений. Повторите попытку позже.|تعذر الوصول إلى خدمة التحديث. يرجى المحاولة لاحقاً.
Checked at startup; you can also check manually.|啟動時會自動檢查；也可隨時手動檢查。|起動時に自動確認します。いつでも手動確認もできます。|시작 시 자동으로 확인하며 언제든 수동으로 확인할 수 있습니다.|Se comprueba al iniciar; también puedes hacerlo manualmente en cualquier momento.|Vérification au démarrage ; vous pouvez aussi vérifier manuellement à tout moment.|Beim Start wird geprüft; Sie können jederzeit manuell prüfen.|A verificação é feita ao iniciar; você também pode verificar manualmente a qualquer momento.|Проверка выполняется при запуске; её также можно запустить вручную в любое время.|يتم التحقق عند بدء التشغيل، ويمكنك التحقق يدوياً في أي وقت.
Release to add files|放開以新增檔案|離してファイルを追加|놓아서 파일 추가|Suelta para añadir archivos|Déposez pour ajouter des fichiers|Loslassen, um Dateien hinzuzufügen|Solte para adicionar arquivos|Отпустите для добавления файлов|أفلت لإضافة الملفات
Images, documents, code, and other attachments|支援圖片、文件、程式碼與其他附件|画像、文書、コード、その他の添付|이미지, 문서, 코드 및 기타 첨부|Imágenes, documentos, código y otros adjuntos|Images, documents, code et autres pièces jointes|Bilder, Dokumente, Code und weitere Anhänge|Imagens, documentos, código e outros anexos|Изображения, документы, код и другие вложения|صور ومستندات وكود ومرفقات أخرى
Service returned {0}|服務傳回 {0}|サービス応答 {0}|서비스 응답 {0}|El servicio devolvió {0}|Le service a renvoyé {0}|Dienst meldete {0}|O serviço retornou {0}|Сервис вернул {0}|أرجعت الخدمة {0}
No valid model response|模型未傳回有效內容|有効なモデル応答がありません|유효한 모델 응답 없음|No hay respuesta válida del modelo|Aucune réponse valide du modèle|Keine gültige Modellantwort|Nenhuma resposta válida do modelo|Нет корректного ответа модели|لا توجد استجابة صالحة من النموذج
Cannot read streaming response|無法讀取串流回應|ストリーミング応答を読めません|스트리밍 응답을 읽을 수 없음|No se puede leer la respuesta en streaming|Impossible de lire la réponse en continu|Streaming-Antwort kann nicht gelesen werden|Não foi possível ler a resposta em streaming|Не удалось прочитать потоковый ответ|تعذر قراءة الاستجابة المتدفقة
Model request failed|模型請求失敗|モデルへのリクエストに失敗|모델 요청 실패|Falló la solicitud al modelo|Échec de la requête au modèle|Modellanfrage fehlgeschlagen|Falha na solicitação ao modelo|Ошибка запроса к модели|فشل طلب النموذج
Pre-send context inspector|傳送前上下文檢查器|送信前のコンテキスト確認|전송 전 컨텍스트 검사|Revisar contexto antes de enviar|Vérifier le contexte avant envoi|Kontext vor dem Senden prüfen|Revisar contexto antes de enviar|Проверка контекста перед отправкой|فحص السياق قبل الإرسال
Click a node to exclude it temporarily|點選節點可暫時排除|クリックで一時的に除外|노드를 클릭하여 임시 제외|Haz clic para excluir temporalmente|Cliquez pour exclure temporairement|Klicken, um vorübergehend auszuschließen|Clique para excluir temporariamente|Нажмите, чтобы временно исключить|انقر على عقدة لاستبعادها مؤقتاً
Sending {0} context nodes; {1} excluded. Excluding a node also excludes its attachments, without deleting any links.|將傳送 {0} 個上下文節點；已排除 {1} 個。排除節點亦會排除其附件，但不會刪除連線。|コンテキスト {0} 件を送信、{1} 件を除外。添付も除外されますが、接続は削除されません。|컨텍스트 {0}개 전송, {1}개 제외. 노드의 첨부도 제외되지만 연결은 삭제되지 않습니다.|Se enviarán {0} nodos; {1} excluidos. Sus adjuntos también se excluyen, sin borrar enlaces.|Envoi de {0} nœuds ; {1} exclus. Leurs pièces jointes sont aussi exclues, sans supprimer les liens.|{0} Kontextknoten werden gesendet; {1} ausgeschlossen. Deren Anhänge werden ebenfalls ausgeschlossen, Verbindungen bleiben erhalten.|Serão enviados {0} nós; {1} excluídos. Seus anexos também são excluídos, sem apagar conexões.|Будет отправлено узлов: {0}; исключено: {1}. Вложения исключаются вместе с узлом, связи сохраняются.|سيُرسل {0} من عقد السياق؛ استُبعد {1}. تُستبعد مرفقات العقدة أيضاً دون حذف الروابط.
Merged context|合併上下文|統合コンテキスト|병합 컨텍스트|Contexto combinado|Contexte fusionné|Zusammengeführter Kontext|Contexto mesclado|Объединённый контекст|سياق مدمج
Referenced context|引用上下文|参照コンテキスト|참조 컨텍스트|Contexto referenciado|Contexte référencé|Referenzierter Kontext|Contexto referenciado|Связанный контекст|سياق مرجعي
Idea background|想法背景|アイデアの背景|아이디어 배경|Trasfondo de la idea|Contexte de l’idée|Ideenhintergrund|Contexto da ideia|Предпосылки идеи|خلفية الفكرة
Inherited context|繼承上下文|継承コンテキスト|상속 컨텍스트|Contexto heredado|Contexte hérité|Geerbter Kontext|Contexto herdado|Унаследованный контекст|سياق موروث
{0} attachments|{0} 個附件|添付 {0} 件|첨부 {0}개|{0} adjuntos|{0} pièces jointes|{0} Anhänge|{0} anexos|Вложений: {0}|{0} مرفقات
New branch · from “{0}”|新分支 · 從「{0}」開始|新しい分岐 ·「{0}」から|새 분기 · “{0}”에서|Nueva rama · desde «{0}»|Nouvelle branche · depuis « {0} »|Neuer Zweig · ab „{0}“|Nova ramificação · de “{0}”|Новая ветвь · от «{0}»|فرع جديد · من «{0}»
Create branch|建立分支|分岐を作成|분기 만들기|Crear rama|Créer une branche|Zweig erstellen|Criar ramificação|Создать ветвь|إنشاء فرع
Create a starting point|建立新起點|開始点を作成|시작점 만들기|Crear punto de partida|Créer un point de départ|Ausgangspunkt erstellen|Criar ponto de partida|Создать отправную точку|إنشاء نقطة بداية
Cancel new starting point|取消建立新起點|開始点の作成を中止|새 시작점 취소|Cancelar punto de partida|Annuler le point de départ|Neuen Ausgangspunkt abbrechen|Cancelar ponto de partida|Отменить новую отправную точку|إلغاء نقطة البداية الجديدة
New starting point · No inherited context|新起點 · 不繼承上下文|新しい開始点 · コンテキスト継承なし|새 시작점 · 상속 컨텍스트 없음|Nuevo inicio · Sin contexto heredado|Nouveau départ · Sans contexte hérité|Neuer Ausgangspunkt · Ohne geerbten Kontext|Novo início · Sem contexto herdado|Новая отправная точка · Без контекста|نقطة بداية جديدة · دون سياق موروث
Describe the task for {0}…|描述交給 {0} 的任務…|{0} に依頼するタスクを入力…|{0}에게 맡길 작업 설명…|Describe la tarea para {0}…|Décrivez la tâche pour {0}…|Aufgabe für {0} beschreiben…|Descreva a tarefa para {0}…|Опишите задачу для {0}…|صف المهمة المطلوبة من {0}…
Ask further|繼續追問|さらに質問|더 질문하기|Profundizar|Approfondir|Weiterfragen|Perguntar mais|Уточнить|اسأل المزيد
Another angle|換個角度|別の視点|다른 관점|Otro enfoque|Autre angle|Anderer Blickwinkel|Outro ângulo|Другой ракурс|زاوية أخرى
Challenge this|反駁它|反論する|반박하기|Cuestionar|Remettre en question|Hinterfragen|Questionar|Оспорить|ناقش الفكرة
Summarize here|總結此處|ここまでを要約|여기까지 요약|Resumir aquí|Résumer ici|Hier zusammenfassen|Resumir aqui|Подвести итог|لخّص هنا
Turn into action|轉為行動|実行に移す|작업으로 전환|Convertir en acción|Passer à l’action|In Aktion umsetzen|Transformar em ação|Перейти к действиям|حوّل إلى إجراء
Merge workspace|合併工作台|統合作業台|병합 작업대|Área de combinación|Espace de fusion|Zusammenführungsbereich|Área de mesclagem|Объединение контекста|مساحة دمج السياق
{0} nodes will be explicit context|{0} 個節點將作為明確上下文|{0} ノードを明示的コンテキストに使用|노드 {0}개를 명시적 컨텍스트로 사용|{0} nodos serán contexto explícito|{0} nœuds serviront de contexte explicite|{0} Knoten dienen als expliziter Kontext|{0} nós serão contexto explícito|{0} узлов будут явным контекстом|ستُستخدم {0} عقد كسياق صريح
Synthesize conclusions|綜合結論|結論をまとめる|결론 종합|Sintetizar conclusiones|Synthétiser les conclusions|Fazit zusammenführen|Sintetizar conclusões|Обобщить выводы|تلخيص الاستنتاجات
Compare side by side|並列比較|並べて比較|나란히 비교|Comparar en paralelo|Comparer côte à côte|Nebeneinander vergleichen|Comparar lado a lado|Сравнить варианты|مقارنة جنباً إلى جنب
Find conflicts|找出衝突|矛盾を見つける|충돌 찾기|Buscar contradicciones|Trouver les contradictions|Widersprüche finden|Encontrar conflitos|Найти противоречия|اكتشاف التعارضات
Plan actions|制定行動|行動を計画|실행 계획|Planificar acciones|Planifier les actions|Aktionen planen|Planejar ações|Составить план действий|تخطيط الإجراءات
The first node is the starting point. Other nodes add context to this branch only; existing links stay unchanged.|第一個節點為起點；其他節點僅加入此次分支的上下文，既有連線不變。|最初のノードが開始点。他のノードはこの分岐のコンテキストにのみ追加され、既存の接続は変わりません。|첫 노드가 시작점입니다. 나머지는 이번 분기의 컨텍스트에만 추가되며 기존 연결은 유지됩니다.|El primer nodo es el inicio. Los demás solo añaden contexto a esta rama; los enlaces no cambian.|Le premier nœud est le départ. Les autres ajoutent du contexte à cette branche seulement ; les liens restent inchangés.|Der erste Knoten ist der Ausgangspunkt. Weitere ergänzen nur den Kontext dieses Zweigs; bestehende Verbindungen bleiben unverändert.|O primeiro nó é o início. Os demais adicionam contexto apenas a esta ramificação; as conexões não mudam.|Первый узел — отправная точка. Остальные добавляют контекст только этой ветви; существующие связи не меняются.|العقدة الأولى هي نقطة البداية. تضيف بقية العقد سياقاً لهذا الفرع فقط وتبقى الروابط الحالية كما هي.
Create merged branch|建立合併分支|統合した分岐を作成|병합 분기 만들기|Crear rama combinada|Créer une branche fusionnée|Zusammengeführten Zweig erstellen|Criar ramificação mesclada|Создать объединённую ветвь|إنشاء فرع مدمج
AI candidate · |AI 候選 · |AI 候補 · |AI 후보 · |Candidato IA · |Proposition IA · |KI-Vorschlag · |Sugestão de IA · |Вариант ИИ · |اقتراح الذكاء الاصطناعي · 
Open in system viewer|使用系統檢視器開啟|システムビューアーで開く|시스템 뷰어로 열기|Abrir con visor del sistema|Ouvrir avec la visionneuse système|Im Systembetrachter öffnen|Abrir no visualizador do sistema|Открыть системным просмотрщиком|فتح بعارض النظام
Click to download|點選下載|クリックしてダウンロード|클릭하여 다운로드|Haz clic para descargar|Cliquez pour télécharger|Zum Herunterladen klicken|Clique para baixar|Нажмите для скачивания|انقر للتنزيل
Expand branch ({0} nodes)|展開分支（{0} 個節點）|分岐を展開（{0} ノード）|분기 펼치기 (노드 {0}개)|Expandir rama ({0} nodos)|Développer la branche ({0} nœuds)|Zweig aufklappen ({0} Knoten)|Expandir ramificação ({0} nós)|Развернуть ветвь ({0} узлов)|توسيع الفرع ({0} عقد)
Collapse branch ({0} nodes)|摺疊分支（{0} 個節點）|分岐を折りたたむ（{0} ノード）|분기 접기 (노드 {0}개)|Contraer rama ({0} nodos)|Réduire la branche ({0} nœuds)|Zweig zuklappen ({0} Knoten)|Recolher ramificação ({0} nós)|Свернуть ветвь ({0} узлов)|طي الفرع ({0} عقد)
New canvas {0}|新畫布 {0}|新規キャンバス {0}|새 캔버스 {0}|Nuevo lienzo {0}|Nouveau canevas {0}|Neue Leinwand {0}|Nova tela {0}|Новый холст {0}|لوحة جديدة {0}
Local model {0}|本機模型 {0}|ローカルモデル {0}|로컬 모델 {0}|Modelo local {0}|Modèle local {0}|Lokales Modell {0}|Modelo local {0}|Локальная модель {0}|نموذج محلي {0}
New model {0}|新模型 {0}|新規モデル {0}|새 모델 {0}|Nuevo modelo {0}|Nouveau modèle {0}|Neues Modell {0}|Novo modelo {0}|Новая модель {0}|نموذج جديد {0}
Connecting…|連線中…|接続中…|연결 중…|Conectando…|Connexion…|Verbindung wird hergestellt…|Conectando…|Подключение…|جارٍ الاتصال…
Connected · {0} models detected|已連線 · 偵測到 {0} 個模型|接続済み · {0} モデル検出|연결됨 · 모델 {0}개 발견|Conectado · {0} modelos detectados|Connecté · {0} modèles détectés|Verbunden · {0} Modelle erkannt|Conectado · {0} modelos detectados|Подключено · Найдено моделей: {0}|متصل · تم اكتشاف {0} نماذج
Connected · No models installed|已連線 · 尚未安裝模型|接続済み · モデル未インストール|연결됨 · 설치된 모델 없음|Conectado · Sin modelos instalados|Connecté · Aucun modèle installé|Verbunden · Keine Modelle installiert|Conectado · Nenhum modelo instalado|Подключено · Модели не установлены|متصل · لا توجد نماذج مثبتة
Loading local archives…|讀取本機存檔中…|ローカルファイルを読込中…|로컬 보관함 로딩 중…|Cargando archivos locales…|Chargement des archives locales…|Lokale Archive werden geladen…|Carregando arquivos locais…|Загрузка локальных архивов…|جارٍ تحميل الأرشيفات المحلية…
AI is generating candidate branches…|AI 正在產生候選分支…|AI が分岐候補を生成中…|AI가 후보 분기를 생성 중…|La IA genera ramas candidatas…|L’IA génère des branches candidates…|KI erstellt Zweigvorschläge…|A IA está gerando ramificações…|ИИ создаёт варианты ветвей…|الذكاء الاصطناعي ينشئ فروعاً مقترحة…
Organizing candidate nodes…|正在整理候選節點…|候補ノードを整理中…|후보 노드 정리 중…|Organizando nodos candidatos…|Organisation des nœuds proposés…|Knotenvorschläge werden geordnet…|Organizando nós candidatos…|Упорядочивание вариантов узлов…|جارٍ تنظيم العقد المقترحة…
No usable node titles returned|未傳回可用的節點標題|有効なノードタイトルがありません|사용 가능한 노드 제목 없음|No se recibieron títulos válidos|Aucun titre de nœud utilisable|Keine nutzbaren Knotentitel erhalten|Nenhum título de nó utilizável|Нет подходящих заголовков узлов|لم تُرجع عناوين عقد صالحة
Candidates ready: select, deselect, or discard them|候選已就緒：可選取、取消選取或全部捨棄|候補を選択、選択解除、または破棄できます|후보 준비 완료: 선택, 선택 해제 또는 삭제|Candidatos listos: selecciona, desmarca o descarta|Propositions prêtes : sélectionnez, désélectionnez ou abandonnez|Vorschläge bereit: auswählen, abwählen oder verwerfen|Sugestões prontas: selecione, desmarque ou descarte|Варианты готовы: выберите, снимите выбор или отбросьте|الاقتراحات جاهزة: حددها أو ألغِ تحديدها أو تجاهلها
Added {0} AI nodes|已加入 {0} 個 AI 節點|AI ノード {0} 件を追加|AI 노드 {0}개 추가됨|{0} nodos de IA añadidos|{0} nœuds IA ajoutés|{0} KI-Knoten hinzugefügt|{0} nós de IA adicionados|Добавлено узлов ИИ: {0}|أُضيفت {0} عقد ذكاء اصطناعي
Cannot inherit from a descendant|無法繼承自己的後代節點|子孫ノードから継承できません|하위 노드에서 상속할 수 없음|No se puede heredar de un descendiente|Impossible d’hériter d’un descendant|Vererbung von Nachfahren nicht möglich|Não é possível herdar de um descendente|Нельзя наследовать от потомка|لا يمكن الوراثة من عقدة تابعة
Merge link created|已建立合併連線|統合接続を作成しました|병합 연결 생성됨|Enlace de combinación creado|Lien de fusion créé|Zusammenführungsverbindung erstellt|Conexão de mesclagem criada|Связь объединения создана|تم إنشاء رابط دمج
Reference link created|已建立引用連線|参照接続を作成しました|참조 연결 생성됨|Enlace de referencia creado|Lien de référence créé|Referenzverbindung erstellt|Conexão de referência criada|Ссылка создана|تم إنشاء رابط مرجعي
Inheritance link created|已建立繼承連線|継承接続を作成しました|상속 연결 생성됨|Enlace de herencia creado|Lien d’héritage créé|Vererbungsverbindung erstellt|Conexão de herança criada|Связь наследования создана|تم إنشاء رابط وراثة
Removed {0} links|已移除 {0} 條連線|接続 {0} 件を削除|연결 {0}개 제거됨|{0} enlaces eliminados|{0} liens supprimés|{0} Verbindungen entfernt|{0} conexões removidas|Удалено связей: {0}|أُزيلت {0} روابط
Copied {0} cards. Press Ctrl+V on the canvas to paste.|已複製 {0} 張卡片。在畫布按 Ctrl+V 貼上。|カード {0} 件をコピー。キャンバスで Ctrl+V で貼り付け。|카드 {0}개 복사됨. 캔버스에서 Ctrl+V로 붙여넣으세요.|{0} tarjetas copiadas. Pulsa Ctrl+V en el lienzo.|{0} cartes copiées. Ctrl+V sur le canevas pour coller.|{0} Karten kopiert. Mit Strg+V auf der Leinwand einfügen.|{0} cartões copiados. Use Ctrl+V na tela para colar.|Скопировано карточек: {0}. Нажмите Ctrl+V на холсте.|نُسخت {0} بطاقات. اضغط Ctrl+V على اللوحة للصقها.
No Wendaflow cards in clipboard|剪貼簿中沒有 Wendaflow 卡片|クリップボードに Wendaflow カードがありません|클립보드에 Wendaflow 카드 없음|No hay tarjetas de Wendaflow en el portapapeles|Aucune carte Wendaflow dans le presse-papiers|Keine Wendaflow-Karten in der Zwischenablage|Nenhum cartão Wendaflow na área de transferência|В буфере нет карточек Wendaflow|لا توجد بطاقات Wendaflow في الحافظة
Pasted {0} cards|已貼上 {0} 張卡片|カード {0} 件を貼り付け|카드 {0}개 붙여넣음|{0} tarjetas pegadas|{0} cartes collées|{0} Karten eingefügt|{0} cartões colados|Вставлено карточек: {0}|لُصقت {0} بطاقات
Project exported|專案已匯出|プロジェクトを出力しました|프로젝트 내보냄|Proyecto exportado|Projet exporté|Projekt exportiert|Projeto exportado|Проект экспортирован|تم تصدير المشروع
Imported {0} nodes|已匯入 {0} 個節點|ノード {0} 件を取込|노드 {0}개 가져옴|{0} nodos importados|{0} nœuds importés|{0} Knoten importiert|{0} nós importados|Импортировано узлов: {0}|تم استيراد {0} عقد
Operation failed: {0}|操作失敗：{0}|操作に失敗：{0}|작업 실패: {0}|Error de operación: {0}|Échec de l’opération : {0}|Vorgang fehlgeschlagen: {0}|Falha na operação: {0}|Ошибка операции: {0}|فشلت العملية: {0}
Invalid Wendaflow WDF file|無效的 Wendaflow WDF 檔案|無効な Wendaflow WDF ファイル|잘못된 Wendaflow WDF 파일|Archivo WDF de Wendaflow no válido|Fichier WDF Wendaflow invalide|Ungültige Wendaflow-WDF-Datei|Arquivo WDF do Wendaflow inválido|Недопустимый WDF-файл Wendaflow|ملف Wendaflow WDF غير صالح
Cannot open artifact|無法開啟產物|成果物を開けません|결과물을 열 수 없음|No se puede abrir el resultado|Impossible d’ouvrir le résultat|Ergebnis kann nicht geöffnet werden|Não foi possível abrir o resultado|Не удалось открыть результат|تعذر فتح الملف الناتج
Cannot download artifact|無法下載產物|成果物をダウンロードできません|결과물을 다운로드할 수 없음|No se puede descargar el resultado|Impossible de télécharger le résultat|Ergebnis kann nicht heruntergeladen werden|Não foi possível baixar o resultado|Не удалось скачать результат|تعذر تنزيل الملف الناتج
Artifact has no local path|產物沒有本機路徑|成果物のローカルパスがありません|결과물의 로컬 경로 없음|El resultado no tiene ruta local|Le résultat n’a pas de chemin local|Ergebnis hat keinen lokalen Pfad|O resultado não tem caminho local|У результата нет локального пути|لا يوجد مسار محلي للملف الناتج
Artifact has no downloadable data|產物沒有可下載資料|ダウンロード可能なデータがありません|다운로드 가능한 데이터 없음|El resultado no tiene datos descargables|Le résultat n’a pas de données téléchargeables|Ergebnis hat keine herunterladbaren Daten|O resultado não tem dados para baixar|Нет данных для скачивания|لا توجد بيانات قابلة للتنزيل
Cannot read artifact file|無法讀取產物檔案|成果物のファイルを読めません|결과물 파일을 읽을 수 없음|No se puede leer el archivo generado|Impossible de lire le fichier produit|Ergebnisdatei kann nicht gelesen werden|Não foi possível ler o arquivo gerado|Не удалось прочитать файл результата|تعذر قراءة الملف الناتج
Cannot open workspace|無法開啟工作目錄|作業フォルダーを開けません|작업 폴더를 열 수 없음|No se puede abrir el espacio de trabajo|Impossible d’ouvrir le dossier de travail|Arbeitsbereich kann nicht geöffnet werden|Não foi possível abrir a pasta de trabalho|Не удалось открыть рабочую папку|تعذر فتح مجلد العمل
License verification failed|授權驗證失敗|ライセンス検証に失敗|라이선스 확인 실패|Error al verificar licencia|Échec de vérification de licence|Lizenzprüfung fehlgeschlagen|Falha ao verificar licença|Ошибка проверки лицензии|فشل التحقق من الترخيص
Image processing failed|圖片處理失敗|画像処理に失敗|이미지 처리 실패|Error al procesar imagen|Échec du traitement d’image|Bildverarbeitung fehlgeschlagen|Falha ao processar imagem|Ошибка обработки изображения|فشلت معالجة الصورة
Cannot read image {0}|無法讀取圖片 {0}|画像 {0} を読めません|이미지 {0} 읽기 실패|No se puede leer la imagen {0}|Impossible de lire l’image {0}|Bild {0} kann nicht gelesen werden|Não foi possível ler a imagem {0}|Не удалось прочитать изображение {0}|تعذر قراءة الصورة {0}
Added {0} attachments. They will be sent with your message.|已加入 {0} 個附件，將隨訊息傳送。|添付 {0} 件を追加。メッセージと一緒に送信されます。|첨부 {0}개 추가됨. 메시지와 함께 전송됩니다.|{0} adjuntos añadidos. Se enviarán con el mensaje.|{0} pièces jointes ajoutées. Elles seront envoyées avec votre message.|{0} Anhänge hinzugefügt. Sie werden mit Ihrer Nachricht gesendet.|{0} anexos adicionados. Serão enviados com sua mensagem.|Добавлено вложений: {0}. Они будут отправлены с сообщением.|أُضيفت {0} مرفقات. ستُرسل مع رسالتك.
Added {0} files to canvas|已在畫布加入 {0} 個檔案|ファイル {0} 件をキャンバスに追加|캔버스에 파일 {0}개 추가됨|{0} archivos añadidos al lienzo|{0} fichiers ajoutés au canevas|{0} Dateien zur Leinwand hinzugefügt|{0} arquivos adicionados à tela|Добавлено файлов на холст: {0}|أُضيفت {0} ملفات إلى اللوحة
Dropped {0} files|已拖放 {0} 個檔案|ファイル {0} 件をドロップ|파일 {0}개 놓음|{0} archivos soltados|{0} fichiers déposés|{0} Dateien abgelegt|{0} arquivos soltos|Перенесено файлов: {0}|أُسقطت {0} ملفات
“{0}” added to the composer|「{0}」已加入輸入框|「{0}」を入力欄に追加|“{0}” 입력창에 추가됨|«{0}» añadido al cuadro de entrada|« {0} » ajouté au champ de saisie|„{0}“ zum Eingabefeld hinzugefügt|“{0}” adicionado à entrada|«{0}» добавлено в поле ввода|أُضيف «{0}» إلى حقل الإدخال
Cannot open canvas database|無法開啟畫布資料庫|キャンバスのデータベースを開けません|캔버스 데이터베이스를 열 수 없음|No se puede abrir la base de datos del lienzo|Impossible d’ouvrir la base du canevas|Leinwanddatenbank kann nicht geöffnet werden|Não foi possível abrir o banco da tela|Не удалось открыть базу холста|تعذر فتح قاعدة بيانات اللوحة
Local cache unavailable. Use Save to write a WDF file.|本機快取不可用，請使用「儲存」寫入 WDF 檔。|キャッシュが利用できません。「保存」で WDF ファイルを保存してください。|로컬 캐시를 사용할 수 없습니다. 저장으로 WDF 파일을 저장하세요.|Caché no disponible. Usa Guardar para crear un WDF.|Cache indisponible. Utilisez Enregistrer pour créer un WDF.|Lokaler Cache nicht verfügbar. Mit Speichern eine WDF-Datei erstellen.|Cache indisponível. Use Salvar para gravar um WDF.|Локальный кэш недоступен. Сохраните файл WDF кнопкой «Сохранить».|التخزين المؤقت المحلي غير متاح. استخدم الحفظ لإنشاء ملف WDF.
Missing API key for {0}|缺少 {0} 的 API 金鑰|{0} の API キーが未設定|{0}의 API 키 없음|Falta la clave API de {0}|Clé API manquante pour {0}|API-Schlüssel für {0} fehlt|Falta a chave API de {0}|Не указан API-ключ для {0}|مفتاح API مفقود لـ {0}
Generation stopped by you.|你已停止產生。|生成を停止しました。|생성을 중지했습니다.|Has detenido la generación.|Vous avez arrêté la génération.|Generierung von Ihnen gestoppt.|Você interrompeu a geração.|Генерация остановлена вами.|أوقفتَ الإنشاء.
{0}. Check the model connection in Settings.|{0}。請在設定中檢查模型連線。|{0}。設定でモデル接続を確認してください。|{0}. 설정에서 모델 연결을 확인하세요.|{0}. Revisa la conexión del modelo en Ajustes.|{0}. Vérifiez la connexion du modèle dans les paramètres.|{0}. Modellverbindung in den Einstellungen prüfen.|{0}. Verifique a conexão do modelo nas configurações.|{0}. Проверьте подключение модели в настройках.|{0}. تحقق من اتصال النموذج في الإعدادات.
No output after 90 seconds. Request stopped; check model load or reduce context.|90 秒未收到輸出。已停止請求；請檢查模型負載或減少上下文。|90 秒間出力がなく停止しました。モデル負荷またはコンテキスト量を確認してください。|90초간 출력이 없어 중지했습니다. 모델 부하를 확인하거나 컨텍스트를 줄이세요.|Sin respuesta tras 90 segundos. Solicitud detenida; revisa la carga o reduce el contexto.|Aucune sortie après 90 secondes. Requête arrêtée ; vérifiez la charge ou réduisez le contexte.|Nach 90 Sekunden keine Ausgabe. Anfrage gestoppt; Modelllast prüfen oder Kontext reduzieren.|Sem resposta após 90 segundos. Solicitação interrompida; verifique a carga ou reduza o contexto.|Нет ответа 90 секунд. Запрос остановлен; проверьте нагрузку модели или сократите контекст.|لا استجابة بعد 90 ثانية. أُوقف الطلب؛ تحقق من حمل النموذج أو قلل السياق.
Continue analyzing this in depth.|請繼續深入分析。|この内容をさらに深く分析してください。|이 내용을 더 깊이 분석해 주세요.|Continúa analizando esto en profundidad.|Poursuivez cette analyse en profondeur.|Analysiere dies weiter im Detail.|Continue analisando isto em profundidade.|Продолжи углублённый анализ.|واصل تحليل هذا بعمق.
Reconsider this from another perspective.|請換個角度重新思考。|別の視点から考え直してください。|다른 관점에서 다시 생각해 주세요.|Reconsidéralo desde otra perspectiva.|Reconsidérez ceci sous un autre angle.|Betrachte dies aus einer anderen Perspektive.|Reconsidere isto de outra perspectiva.|Рассмотри это с другой точки зрения.|أعد النظر من منظور آخر.
Find weaknesses, counterexamples, and risks in this view.|請找出此觀點的漏洞、反例與風險。|この見解の弱点、反例、リスクを見つけてください。|이 관점의 약점, 반례와 위험을 찾아 주세요.|Busca debilidades, contraejemplos y riesgos de esta postura.|Trouvez les faiblesses, contre-exemples et risques de ce point de vue.|Finde Schwächen, Gegenbeispiele und Risiken dieser Ansicht.|Encontre falhas, contraexemplos e riscos nesta visão.|Найди слабые места, контрпримеры и риски этой позиции.|ابحث عن نقاط الضعف والأمثلة المضادة والمخاطر في هذا الرأي.
Summarize the key conclusions of the context above.|請總結以上上下文的核心結論。|上記のコンテキストの主要な結論を要約してください。|위 컨텍스트의 핵심 결론을 요약해 주세요.|Resume las conclusiones clave del contexto anterior.|Résumez les conclusions clés du contexte ci-dessus.|Fasse die wichtigsten Schlussfolgerungen des obigen Kontexts zusammen.|Resuma as principais conclusões do contexto acima.|Обобщи ключевые выводы из контекста выше.|لخّص الاستنتاجات الرئيسية للسياق أعلاه.
Turn the above into actionable steps.|請將以上內容轉為可執行步驟。|上記の内容を実行可能な手順にしてください。|위 내용을 실행 가능한 단계로 바꿔 주세요.|Convierte lo anterior en pasos ejecutables.|Transformez ce qui précède en étapes concrètes.|Wandle das Obige in umsetzbare Schritte um.|Transforme o conteúdo acima em etapas executáveis.|Преобразуй сказанное выше в конкретные шаги.|حوّل ما سبق إلى خطوات قابلة للتنفيذ.
Based on the {0} merged nodes: {1}.|請基於合併的 {0} 個節點：{1}。|統合された {0} ノードに基づき：{1}。|병합된 노드 {0}개를 바탕으로: {1}.|Basándote en los {0} nodos combinados: {1}.|À partir des {0} nœuds fusionnés : {1}.|Auf Grundlage der {0} zusammengeführten Knoten: {1}.|Com base nos {0} nós mesclados: {1}.|На основе {0} объединённых узлов: {1}.|بناءً على {0} عقد مدمجة: {1}.
Dropped {0} files. Double-click to add details, or use + to ask AI.|已拖放 {0} 個檔案。雙擊補充說明，或使用 + 向 AI 提問。|ファイル {0} 件を追加。ダブルクリックで詳細を入力、+ で AI に質問できます。|파일 {0}개 추가됨. 두 번 클릭하여 설명하거나 +로 AI에게 질문하세요.|{0} archivos soltados. Doble clic para añadir detalles o + para preguntar a la IA.|{0} fichiers déposés. Double-cliquez pour préciser ou utilisez + pour interroger l’IA.|{0} Dateien abgelegt. Doppelklick für Details oder + für eine KI-Frage.|{0} arquivos soltos. Clique duas vezes para detalhes ou use + para perguntar à IA.|Перенесено файлов: {0}. Дважды щёлкните для описания или нажмите + для вопроса ИИ.|أُسقطت {0} ملفات. انقر مرتين لإضافة تفاصيل أو استخدم + لسؤال الذكاء الاصطناعي.
Please interpret the uploaded images or files.|請理解並描述上傳的圖片或檔案。|添付した画像やファイルを説明してください。|업로드한 이미지나 파일을 해석해 주세요.|Interpreta las imágenes o archivos subidos.|Interprétez les images ou fichiers importés.|Interpretiere die hochgeladenen Bilder oder Dateien.|Interprete as imagens ou arquivos enviados.|Проанализируй загруженные изображения или файлы.|فسّر الصور أو الملفات المرفوعة.
Local Codex|本機 Codex|ローカル Codex|로컬 Codex|Codex local|Codex local|Lokales Codex|Codex local|Локальный Codex|Codex محلي
{0} execution results|{0} 執行結果|{0} の実行結果|{0} 실행 결과|Resultados de {0}|Résultats de {0}|Ausführungsergebnisse von {0}|Resultados de {0}|Результаты выполнения {0}|نتائج تنفيذ {0}
{0} execution failed: {1}|{0} 執行失敗：{1}|{0} の実行に失敗：{1}|{0} 실행 실패: {1}|Falló la ejecución de {0}: {1}|Échec de l’exécution de {0} : {1}|Ausführung von {0} fehlgeschlagen: {1}|Falha na execução de {0}: {1}|Ошибка выполнения {0}: {1}|فشل تنفيذ {0}: {1}
Injected {0} context nodes and {1} attachments.|已注入 {0} 個上下文節點和 {1} 個附件。|コンテキスト {0} ノードと添付 {1} 件を追加。|컨텍스트 노드 {0}개와 첨부 {1}개 주입됨.|Se añadieron {0} nodos y {1} adjuntos al contexto.|{0} nœuds et {1} pièces jointes injectés.|{0} Kontextknoten und {1} Anhänge eingefügt.|{0} nós de contexto e {1} anexos inseridos.|Добавлено узлов контекста: {0}, вложений: {1}.|أُضيفت {0} عقد سياق و{1} مرفقات.
Starting from scratch, without inherited nodes.|從零開始，不繼承節點。|ノードを継承せずに最初から開始。|상속 노드 없이 처음부터 시작.|Inicio desde cero, sin nodos heredados.|Départ de zéro, sans nœuds hérités.|Neustart ohne geerbte Knoten.|Começando do zero, sem nós herdados.|Начало с нуля, без унаследованных узлов.|البدء من الصفر دون عقد موروثة.
Codex returned {0}|Codex 傳回 {0}|Codex が {0} を返しました|Codex 반환: {0}|Codex devolvió {0}|Codex a renvoyé {0}|Codex meldete {0}|Codex retornou {0}|Codex вернул {0}|أرجع Codex ‏{0}
Preparing {0} context nodes and connecting…|正在整理 {0} 個上下文節點並連線…|コンテキスト {0} ノードを準備して接続中…|컨텍스트 노드 {0}개 준비 및 연결 중…|Preparando {0} nodos y conectando…|Préparation de {0} nœuds et connexion…|{0} Kontextknoten werden vorbereitet und Verbindung hergestellt…|Preparando {0} nós e conectando…|Подготовка {0} узлов контекста и подключение…|جارٍ إعداد {0} عقد سياق والاتصال…
Waiting for first output ({0} seconds)…|等待首次輸出（{0} 秒）…|最初の出力を待機中（{0} 秒）…|첫 출력 대기 중 ({0}초)…|Esperando primera respuesta ({0} segundos)…|Attente de la première réponse ({0} secondes)…|Warte auf erste Ausgabe ({0} Sekunden)…|Aguardando primeira resposta ({0} segundos)…|Ожидание первого ответа ({0} секунд)…|بانتظار أول استجابة ({0} ثانية)…
Thinking…|思考中…|思考中…|생각 중…|Pensando…|Réflexion…|Denkt nach…|Pensando…|Размышление…|جارٍ التفكير…
Request queued…|請求排隊中…|リクエスト待機中…|요청 대기 중…|Solicitud en cola…|Requête en attente…|Anfrage in Warteschlange…|Solicitação na fila…|Запрос в очереди…|الطلب في قائمة الانتظار…
`;
