const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('notificationManager', {
  settings: () => ipcRenderer.invoke('manager:settings'),
  saveSettings: (value) => ipcRenderer.invoke('manager:save-settings', value),
  status: () => ipcRenderer.invoke('manager:status'),
  start: () => ipcRenderer.invoke('manager:start'),
  stop: () => ipcRenderer.invoke('manager:stop'),
  send: (value) => ipcRenderer.invoke('manager:send', value),
  release: () => ipcRenderer.invoke('manager:release'),
  saveRelease: (value) => ipcRenderer.invoke('manager:save-release', value),
  devices: (search, offset) => ipcRenderer.invoke('manager:devices', search, offset),
  licenses: () => ipcRenderer.invoke('manager:licenses'),
  createLicense: (value) => ipcRenderer.invoke('manager:create-license', value),
  revokeLicense: (id) => ipcRenderer.invoke('manager:revoke-license', id),
  freezeLicense: (id) => ipcRenderer.invoke('manager:freeze-license', id),
  removeLicenseDevice: (id, deviceId) => ipcRenderer.invoke('manager:remove-license-device', id, deviceId),
  audit: () => ipcRenderer.invoke('manager:audit'),
  notificationHistory: () => ipcRenderer.invoke('manager:notification-history'),
  revokeNotification: (id) => ipcRenderer.invoke('manager:revoke-notification', id),
  campaigns: () => ipcRenderer.invoke('manager:campaigns'),
  createCampaign: (value) => ipcRenderer.invoke('manager:create-campaign', value),
  sendCampaign: (id) => ipcRenderer.invoke('manager:send-campaign', id),
  revokeCampaign: (id) => ipcRenderer.invoke('manager:revoke-campaign', id),
  backup: () => ipcRenderer.invoke('manager:backup'),
  openFolder: () => ipcRenderer.invoke('manager:open-folder'),
  copy: (value) => ipcRenderer.invoke('manager:copy', value),
});
