import crypto from 'node:crypto';
import http from 'node:http';
import express from 'express';
import cors from 'cors';
import pg from 'pg';
import { WebSocketServer, WebSocket } from 'ws';

const { Pool } = pg;
const port = Number(process.env.PORT || 8788);
const adminToken = process.env.WENDAFLOW_ADMIN_TOKEN || '';
const licenseSecret = process.env.WENDAFLOW_LICENSE_SECRET || '';
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const clients = new Map();
const rateBuckets = new Map();
const app = express();
app.disable('x-powered-by'); app.use(cors({ origin: process.env.CORS_ORIGIN || true })); app.use(express.json({ limit: '64kb' }));

const q = (text, params = []) => pool.query(text, params);
function secure(req, res, next) { if (!adminToken || req.get('x-admin-token') !== adminToken) return res.status(401).json({ error: 'Unauthorized' }); next(); }
function rateLimit(limit, windowMs) { return (req,res,next) => { const key=`${req.ip}:${req.path}`, now=Date.now(), values=(rateBuckets.get(key)||[]).filter(time=>now-time<windowMs); if(values.length>=limit)return res.status(429).json({error:'Too many requests. Try again later.'}); values.push(now); rateBuckets.set(key,values); next(); }; }
function hash(code) { return crypto.createHash('sha256').update(String(code).trim().toUpperCase()).digest('hex'); }
function code() { return `WDF-${crypto.randomBytes(4).toString('hex').toUpperCase()}-${crypto.randomBytes(4).toString('hex').toUpperCase()}-${crypto.randomBytes(4).toString('hex').toUpperCase()}`; }
function codeCipherKey() { return crypto.createHash('sha256').update(`wendaflow-license-code:${licenseSecret}`).digest(); }
function encryptCode(value) { const iv = crypto.randomBytes(12), cipher = crypto.createCipheriv('aes-256-gcm', codeCipherKey(), iv), encrypted = Buffer.concat([cipher.update(String(value), 'utf8'), cipher.final()]); return `${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${encrypted.toString('base64url')}`; }
function decryptCode(value) { try { const [ivValue, tagValue, encryptedValue] = String(value || '').split('.'); if (!ivValue || !tagValue || !encryptedValue || !licenseSecret) return ''; const decipher = crypto.createDecipheriv('aes-256-gcm', codeCipherKey(), Buffer.from(ivValue, 'base64url')); decipher.setAuthTag(Buffer.from(tagValue, 'base64url')); return Buffer.concat([decipher.update(Buffer.from(encryptedValue, 'base64url')), decipher.final()]).toString('utf8'); } catch { return ''; } }
function sign(payload) { const value = Buffer.from(JSON.stringify(payload)).toString('base64url'); return `${value}.${crypto.createHmac('sha256', licenseSecret).update(value).digest('base64url')}`; }
function parse(token) { const [value, signature] = String(token || '').split('.'); const wanted = crypto.createHmac('sha256', licenseSecret).update(value || '').digest('base64url'); const a = Buffer.from(signature || ''); const b = Buffer.from(wanted); if (!value || a.length !== b.length || !crypto.timingSafeEqual(a, b)) return null; try { return JSON.parse(Buffer.from(value, 'base64url').toString('utf8')); } catch { return null; } }
function grant(row, deviceId) { return { licenseId: row.id, tier: row.tier, expiresAt: row.expires_at || '', deviceId, issuedAt: new Date().toISOString() }; }
async function init() {
  await q(`CREATE TABLE IF NOT EXISTS app_settings (key text PRIMARY KEY, value jsonb NOT NULL);
    CREATE TABLE IF NOT EXISTS devices (id text PRIMARY KEY, app_version text NOT NULL DEFAULT 'unknown', language text NOT NULL DEFAULT 'unknown', created_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS notifications (id uuid PRIMARY KEY, title text NOT NULL, body text NOT NULL DEFAULT '', kind text NOT NULL DEFAULT 'info', canvas_id text NOT NULL DEFAULT '', node_id text NOT NULL DEFAULT '', requires_ack boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS notification_deliveries (notification_id uuid REFERENCES notifications(id) ON DELETE CASCADE, device_id text REFERENCES devices(id) ON DELETE CASCADE, read_at timestamptz, acknowledged_at timestamptz, PRIMARY KEY(notification_id, device_id));
    CREATE INDEX IF NOT EXISTS deliveries_device_idx ON notification_deliveries(device_id, read_at, notification_id);
    CREATE TABLE IF NOT EXISTS licenses (id uuid PRIMARY KEY, code_hash text UNIQUE NOT NULL, code_ciphertext text, tier text NOT NULL, label text NOT NULL DEFAULT '', max_devices integer NOT NULL DEFAULT 1, expires_at timestamptz, revoked_at timestamptz, frozen_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS license_devices (license_id uuid REFERENCES licenses(id) ON DELETE CASCADE, device_id text REFERENCES devices(id) ON DELETE CASCADE, activated_at timestamptz NOT NULL DEFAULT now(), last_validated_at timestamptz NOT NULL DEFAULT now(), app_version text NOT NULL DEFAULT 'unknown', PRIMARY KEY(license_id, device_id));
    CREATE INDEX IF NOT EXISTS license_devices_device_idx ON license_devices(device_id);
    CREATE TABLE IF NOT EXISTS audit_logs (id uuid PRIMARY KEY, action text NOT NULL, detail jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
    ALTER TABLE licenses ADD COLUMN IF NOT EXISTS frozen_at timestamptz;
    ALTER TABLE licenses ADD COLUMN IF NOT EXISTS code_ciphertext text;`);
  await q(`INSERT INTO app_settings(key,value) VALUES ('release', $1) ON CONFLICT (key) DO NOTHING`, [JSON.stringify({ latestVersion: '0.1.0', downloadUrl: '', releaseNotes: '', publishedAt: '' })]);
}
async function upsertDevice(id, version, language) { await q(`INSERT INTO devices(id,app_version,language) VALUES($1,$2,$3) ON CONFLICT(id) DO UPDATE SET app_version=EXCLUDED.app_version, language=EXCLUDED.language, last_seen_at=now()`, [id, String(version || 'unknown').slice(0,64), String(language || 'unknown').slice(0,32)]); }
async function audit(action, detail = {}) { await q('INSERT INTO audit_logs(id,action,detail) VALUES($1,$2,$3)', [crypto.randomUUID(), action, JSON.stringify(detail)]); }
async function targetDevices(audience, deviceId, targetVersion, targetLanguage) { const rules = { all: ['SELECT id FROM devices', []], device: ['SELECT id FROM devices WHERE id=$1', [deviceId]], version: ['SELECT id FROM devices WHERE app_version=$1', [targetVersion]], language: ['SELECT id FROM devices WHERE language=$1', [targetLanguage]] }; const [sql, values] = rules[audience] || rules.device; return (await q(sql, values)).rows.map((row) => row.id); }
async function release() { return (await q(`SELECT value FROM app_settings WHERE key='release'`)).rows[0]?.value || { latestVersion: '0.1.0', downloadUrl:'', releaseNotes:'', publishedAt:'' }; }

app.get('/health', async (_req, res) => { const [{ rows: devices }] = await Promise.all([q('SELECT count(*)::int AS count FROM devices')]); const current = await release(); res.json({ ok: true, onlineDevices: clients.size, registeredDevices: devices[0].count, latestVersion: current.latestVersion, uptimeSeconds: Math.round(process.uptime()), memoryBytes: process.memoryUsage().rss, storage: 'postgresql' }); });
app.get('/v1/client/latest', async (_req,res) => res.json(await release()));
app.put('/v1/client/latest', secure, async (req,res) => { const { latestVersion, downloadUrl='', releaseNotes='' } = req.body || {}; if (!latestVersion) return res.status(400).json({error:'latestVersion is required'}); const value={latestVersion:String(latestVersion).slice(0,64),downloadUrl:String(downloadUrl).slice(0,1000),releaseNotes:String(releaseNotes).slice(0,3000),publishedAt:new Date().toISOString()}; await q(`UPDATE app_settings SET value=$1 WHERE key='release'`,[JSON.stringify(value)]); res.json(value); });
app.post('/v1/notifications', secure, async (req,res) => { const { audience='device', deviceId='', targetVersion='', targetLanguage='', title, body='', kind='info', canvasId='', nodeId='', requiresAcknowledgement=false }=req.body||{}; if(!title)return res.status(400).json({error:'title is required'}); if(!['device','all','version','language'].includes(audience))return res.status(400).json({error:'Unknown audience'}); if((audience==='device'&&!deviceId)||(audience==='version'&&!targetVersion)||(audience==='language'&&!targetLanguage))return res.status(400).json({error:'Target is required'}); const recipients=await targetDevices(audience,deviceId,targetVersion,targetLanguage); if(!recipients.length)return res.status(404).json({error:'No matching registered devices'}); const id=crypto.randomUUID(), createdAt=new Date().toISOString(), payload={id,title:String(title).slice(0,180),body:String(body).slice(0,1000),kind,canvasId,nodeId,requiresAcknowledgement:!!requiresAcknowledgement,createdAt,read:false}; const client=await pool.connect(); try{await client.query('BEGIN');await client.query('INSERT INTO notifications(id,title,body,kind,canvas_id,node_id,requires_ack,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[id,payload.title,payload.body,kind,String(canvasId),String(nodeId),!!requiresAcknowledgement,createdAt]);await client.query('INSERT INTO notification_deliveries(notification_id,device_id) SELECT $1, unnest($2::text[])',[id,recipients]);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}let delivered=0;for(const device of recipients){for(const socket of clients.get(device)||[])if(socket.readyState===WebSocket.OPEN){socket.send(JSON.stringify({type:'notification',notification:payload}));delivered++;}}res.status(201).json({audience,recipientCount:recipients.length,delivered,createdAt}); });
app.get('/v1/devices', secure, async (req,res) => { const limit=Math.max(1,Math.min(200,Number(req.query.limit)||50)), offset=Math.max(0,Number(req.query.offset)||0), search=String(req.query.search||''); const where=search?'WHERE id ILIKE $1 OR app_version ILIKE $1 OR language ILIKE $1':''; const params=search?[`%${search}%`,limit,offset]:[limit,offset]; const rows=await q(`SELECT id,app_version AS "appVersion",language,created_at AS "createdAt",last_seen_at AS "lastSeenAt" FROM devices ${where} ORDER BY last_seen_at DESC LIMIT $${search?2:1} OFFSET $${search?3:2}`,params); const total=await q(`SELECT count(*)::int AS count FROM devices ${where}`,search?[`%${search}%`]:[]); res.json({devices:rows.rows,total:total.rows[0].count,limit,offset}); });
app.get('/v1/devices/:deviceId/notifications', async (req,res) => { const rows=await q(`SELECT n.id,n.title,n.body,n.kind,n.canvas_id AS "canvasId",n.node_id AS "nodeId",n.requires_ack AS "requiresAcknowledgement",n.created_at AS "createdAt",d.read_at AS "readAt",d.acknowledged_at AS "acknowledgedAt" FROM notification_deliveries d JOIN notifications n ON n.id=d.notification_id WHERE d.device_id=$1 ORDER BY n.created_at DESC LIMIT 120`,[req.params.deviceId]);res.json({notifications:rows.rows.map(row=>({...row,read:!!row.readAt}))}); });
app.post('/v1/licenses/activate', rateLimit(10,15*60*1000), async (req,res) => { if(!licenseSecret)return res.status(503).json({error:'License service is not configured'});const{code:raw,deviceId,appVersion='unknown'}=req.body||{};if(!raw||!deviceId)return res.status(400).json({error:'Activation code and device ID are required'});await upsertDevice(deviceId,appVersion,'unknown');const found=await q('SELECT * FROM licenses WHERE code_hash=$1',[hash(raw)]);const license=found.rows[0];if(!license||license.revoked_at||license.frozen_at)return res.status(403).json({error:'Activation code is invalid, frozen, or revoked'});if(license.expires_at&&new Date(license.expires_at)<new Date())return res.status(403).json({error:'Activation code has expired'});const existing=await q('SELECT 1 FROM license_devices WHERE license_id=$1 AND device_id=$2',[license.id,deviceId]);let displacedDeviceId='';if(!existing.rowCount){const seats=await q('SELECT device_id FROM license_devices WHERE license_id=$1 ORDER BY activated_at ASC LIMIT 1 OFFSET $2',[license.id,Math.max(0,license.max_devices-1)]);if(seats.rowCount){displacedDeviceId=seats.rows[0].device_id;await q('DELETE FROM license_devices WHERE license_id=$1 AND device_id=$2',[license.id,displacedDeviceId]);}}await q(`INSERT INTO license_devices(license_id,device_id,app_version) VALUES($1,$2,$3) ON CONFLICT(license_id,device_id) DO UPDATE SET last_validated_at=now(),app_version=EXCLUDED.app_version`,[license.id,deviceId,String(appVersion).slice(0,64)]);await audit('license.activated',{licenseId:license.id,deviceId,displacedDeviceId});const value=grant(license,deviceId);res.json({license:{...value,token:sign(value)},displacedDeviceId}); });
app.post('/v1/licenses/validate', rateLimit(60,60*1000), async (req,res) => { const {token,deviceId,appVersion='unknown'}=req.body||{};const value=parse(token);if(!value||value.deviceId!==deviceId)return res.status(403).json({error:'Invalid license token'});const result=await q(`SELECT l.* FROM licenses l JOIN license_devices d ON d.license_id=l.id WHERE l.id=$1 AND d.device_id=$2`,[value.licenseId,deviceId]);const license=result.rows[0];if(!license||license.revoked_at||license.frozen_at||(license.expires_at&&new Date(license.expires_at)<new Date()))return res.status(403).json({error:'License is no longer valid'});await q('UPDATE license_devices SET last_validated_at=now(),app_version=$3 WHERE license_id=$1 AND device_id=$2',[license.id,deviceId,String(appVersion).slice(0,64)]);const refreshed=grant(license,deviceId);res.json({license:{...refreshed,token:sign(refreshed)}}); });
app.post('/v1/admin/licenses', secure, async (req,res) => { const{tier='pro',label='',maxDevices=1,expiresAt='',quantity=1}=req.body||{};const created=[];for(let i=0;i<Math.max(1,Math.min(1000,Number(quantity)||1));i++){const raw=code(),id=crypto.randomUUID();const inserted=await q('INSERT INTO licenses(id,code_hash,code_ciphertext,tier,label,max_devices,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[id,hash(raw),encryptCode(raw),String(tier).slice(0,32),String(label).slice(0,120),Math.max(1,Math.min(50,Number(maxDevices)||1)),expiresAt||null]);created.push({code:raw,license:{id,tier:inserted.rows[0].tier,label:inserted.rows[0].label,maxDevices:inserted.rows[0].max_devices,expiresAt:inserted.rows[0].expires_at,revoked:false,frozen:false,createdAt:inserted.rows[0].created_at,code:raw,codeAvailable:true,activatedDevices:[]}});}await audit('license.created',{quantity:created.length,tier,maxDevices});res.status(201).json(created.length===1?created[0]:{created}); });
app.get('/v1/admin/licenses', secure, async (_req,res) => { const rows=await q(`SELECT l.*,COALESCE(json_agg(json_build_object('deviceId',d.device_id,'activatedAt',d.activated_at,'lastValidatedAt',d.last_validated_at,'appVersion',d.app_version)) FILTER(WHERE d.device_id IS NOT NULL),'[]') AS devices FROM licenses l LEFT JOIN license_devices d ON d.license_id=l.id GROUP BY l.id ORDER BY l.created_at DESC`);res.json({licenses:rows.rows.map(row=>{const visibleCode=decryptCode(row.code_ciphertext);return{id:row.id,tier:row.tier,label:row.label,maxDevices:row.max_devices,expiresAt:row.expires_at,revoked:!!row.revoked_at,frozen:!!row.frozen_at,createdAt:row.created_at,code:visibleCode,codeAvailable:!!visibleCode,activatedDevices:row.devices};})}); });
app.post('/v1/admin/licenses/:id/revoke', secure, async(req,res)=>{const r=await q('UPDATE licenses SET revoked_at=now() WHERE id=$1 RETURNING id',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'License not found'});await audit('license.revoked',{licenseId:req.params.id});res.json({ok:true});});
app.post('/v1/admin/licenses/:id/freeze',secure,async(req,res)=>{const r=await q('UPDATE licenses SET frozen_at=CASE WHEN frozen_at IS NULL THEN now() ELSE NULL END WHERE id=$1 RETURNING frozen_at',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'License not found'});await audit(r.rows[0].frozen_at?'license.frozen':'license.unfrozen',{licenseId:req.params.id});res.json({ok:true});});
app.delete('/v1/admin/licenses/:id/devices/:deviceId',secure,async(req,res)=>{await q('DELETE FROM license_devices WHERE license_id=$1 AND device_id=$2',[req.params.id,req.params.deviceId]);await audit('license.device_unbound',{licenseId:req.params.id,deviceId:req.params.deviceId});res.json({ok:true});});
app.get('/v1/admin/audit',secure,async(_req,res)=>{const rows=await q('SELECT id,action,detail,created_at AS "createdAt" FROM audit_logs ORDER BY created_at DESC LIMIT 300');res.json({entries:rows.rows});});

const server=http.createServer(app),wss=new WebSocketServer({noServer:true});
wss.on('connection',async(socket,deviceId,version,language)=>{const group=clients.get(deviceId)||new Set();group.add(socket);clients.set(deviceId,group);await upsertDevice(deviceId,version,language);socket.send(JSON.stringify({type:'connected',deviceId}));const rows=await q(`SELECT n.id,n.title,n.body,n.kind,n.canvas_id AS "canvasId",n.node_id AS "nodeId",n.requires_ack AS "requiresAcknowledgement",n.created_at AS "createdAt",d.read_at AS "readAt" FROM notification_deliveries d JOIN notifications n ON n.id=d.notification_id WHERE d.device_id=$1 ORDER BY n.created_at DESC LIMIT 120`,[deviceId]);socket.send(JSON.stringify({type:'history',notifications:rows.rows.map(row=>({...row,read:!!row.readAt}))}));socket.on('close',()=>{group.delete(socket);if(!group.size)clients.delete(deviceId);});});
server.on('upgrade',(request,socket,head)=>{const url=new URL(request.url||'/',`http://${request.headers.host}`),deviceId=url.searchParams.get('deviceId');if(url.pathname!=='/v1/realtime'||!deviceId)return socket.destroy();wss.handleUpgrade(request,socket,head,ws=>wss.emit('connection',ws,deviceId,url.searchParams.get('version'),url.searchParams.get('language')));});
init().then(()=>server.listen(port,'0.0.0.0',()=>console.log(`Wendaflow PostgreSQL API on ${port}`))).catch(error=>{console.error(error);process.exit(1);});
